version: '3.1'

services:

  postgresTest:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgresTest
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    # volumes:
    #   - ./db_scripts:/docker-entrypoint-initdb.d

                  
    

  adminer:
   image: adminer
   ports:
     - "8080:8080"
   depends_on:
     - postgresTest
   links:
    - postgresTest