version: '3.1'

services:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: vision
      MYSQL_PASSWORD: vision
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqlTest
    # volumes:
    #   - ./db_scripts:/docker-entrypoint-initdb.d
    
  adminer:
   image: adminer
   ports:
     - "8080:8080"
   depends_on:
     - mysql
   links:
    - mysql